# Scalars (Rank 0 Tensors)

## Python

In [13]:
x_py = 25
x_py_float = 25.0
y_py = 5

print(x)
print(type(x))
print(x_py + y_py)
print(type(x_py + y_py))
print(x_py_float + y_py)
print(type(x_py_float + y_py))

25
<class 'int'>
30
<class 'int'>
30.0
<class 'float'>


## Numpy

In [19]:
import numpy as np
x_np = np.int16(25)
x_np_float = np.float64(25)
y_np = np.int64(5)

sum_np = x_np + y_np
sum_np_float = x_np_float + y_np
print(x_np)
print(type(x_np))
print(sum_np)
print(type(sum_np))
print(type(sum_np_float))


25
<class 'numpy.int16'>
30
<class 'numpy.int64'>
<class 'numpy.float64'>


## Pytorch

In [57]:
import torch

x_pt = torch.tensor(25) # type specification optional, e.g.: dtype=torch.float16
y_pt = torch.tensor(5, dtype=torch.float16)
print(x_pt)
print(x_pt.shape)
sum_pt = x_pt + y_pt
print(sum_pt)
print(type(sum_pt))
print(sum_pt.numpy().shape)

tensor(25)
torch.Size([])
tensor(30., dtype=torch.float16)
<class 'torch.Tensor'>
()


## Tensorflow

Tensors created with a wrapper, all of which you can read about here:

    tf.Variable
    tf.constant
    tf.placeholder
    tf.SparseTensor


In [50]:
import tensorflow as tf
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
# Transform to Numpy
print(rank_0_tensor.numpy())
x_tf = tf.Variable(25, dtype=tf.int16) # dtype is optional
print(x_tf)
print(x_tf.shape)
y_tf = tf.Variable(5, dtype=tf.int16)
sum_tf = x_tf + y_tf
tf_sum = tf.add(x_tf, y_tf)
print(tf_sum)
print(tf_sum.numpy())
type(tf_sum.numpy())

tf_float = tf.Variable(25., dtype=tf.float16)
print(tf_float)
try:
    tf_sum2 = tf.add(x_tf, tf_float)
    print(tf_sum2.numpy())
    print(type(tf_sum2))    
except:
    print("*ERROR* Cannot add int and float")



tf.Tensor(4, shape=(), dtype=int32)
4
<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>
()
tf.Tensor(30, shape=(), dtype=int16)
30
<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>
*ERROR* Cannot add int and float


## JAX

In [20]:
import jax.numpy as jnp

In [25]:
x_jx = jnp.int32(25)
y_jx = jnp.float32(5)
sum_jx = x_jx + y_jx
print(x_jx)
print(type(x_jx))
print(sum_jx)
print(type(sum_jx))

25
<class 'jaxlib.xla_extension.ArrayImpl'>
30.0
<class 'jaxlib.xla_extension.ArrayImpl'>


# Vector (Rank 1 Tensors)

## Numpy

In [73]:
# NumPy: mutable arrays
x_arr_np = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
y_arr_np = np.arange(10)
z_arr_np = np.zeros(3) 

x_arr_np[0] = 10
print(x_arr_np)
print(len(x_arr_np))
print(x_arr_np.shape)
print(type(x_arr_np))
print(type(x_arr_np[0]))

# Transposing a regular 1-D array has no effect...
x_arr_np_t = x_arr_np.T
print(x_arr_np_t)



[10  2  5]
3
(3,)
<class 'numpy.ndarray'>
<class 'numpy.int64'>
[0 1 2 3 4 5 6 7 8 9]


## JAX

In [75]:
x_arr_jx = jnp.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
y_arr_jx = jnp.arange(10)
z_arr_jx = jnp.zeros(3) 

print(x_arr_jx)
print(type(x_arr_jx))
print(y_arr_jx)
print(type(y_arr_jx))
print(z_arr_jx)
print(type(z_arr_jx))

# Transposing a regular 1-D array has no effect...
x_arr_jx_t = x_arr_jx.T
print(x_arr_jx_t)
print(jnp.transpose(x_arr_jx_t))

[25  2  5]
<class 'jaxlib.xla_extension.ArrayImpl'>
[0 1 2 3 4 5 6 7 8 9]
<class 'jaxlib.xla_extension.ArrayImpl'>
[0. 0. 0.]
<class 'jaxlib.xla_extension.ArrayImpl'>
[25  2  5]
[25  2  5]


In [69]:
# JAX: has immutable arrays
%xmode minimal
y_jx_arr[0] = 10

Exception reporting mode: Minimal


TypeError: '<class 'jaxlib.xla_extension.ArrayImpl'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html

In [32]:
# To Update
y_jx_arr = x_jx_arr.at[0].set(10)
print(x_jx_arr)
print(y_jx_arr)

[0 1 2 3 4 5 6 7 8 9]
[10  1  2  3  4  5  6  7  8  9]


## Pytorch

In [81]:
x_pt_arr = torch.tensor([25, 2, 5])
print(x_pt_arr)

# Orthogonal Vectors
print(
    torch.dot(
        torch.tensor([1, 0]), 
        torch.tensor([0, 1])
        )
    )


tensor([25,  2,  5])
tensor(0)


# Tensorflow

In [86]:
x_tf = tf.Variable([25, 2, 5])
x_tf

# Orthogonal Vectors
print(
    tf.tensordot(
        tf.Variable([1, 0]), 
        tf.Variable([0, 1]),
        1
        )
    )


tf.Tensor(0, shape=(), dtype=int32)


# Matrices (Rank 2 Tensors)

## Numpy

In [93]:
# Use array() with nested brackets: 
X = np.array([[25, 2], [5, 26], [3, 7]])
print(X)
print(X.shape)
print(X.size)
print()
# Select left column of matrix X (zero-indexed)
print(X[:,0])

# Select middle row of matrix X: 
print(X[1,:])

# Another slicing-by-index example: 
print(X[0:2, 0:2])

[[25  2]
 [ 5 26]
 [ 3  7]]
(3, 2)
6

[25  5  3]
[ 5 26]
[[25  2]
 [ 5 26]]


In [95]:
A = jnp.array([[1, -1, 3],[ 3, 5, 1],[7, 0, 9]])
print(A)
print(A.shape)
print(A.size)
print()
# Select left column of matrix A (zero-indexed)
print(A[:,0])

# Select middle row of matrix A: 
print(A[1,:])

# Another slicing-by-index example: 
print(A[0:2, 0:2])

[[ 1 -1  3]
 [ 3  5  1]
 [ 7  0  9]]
(3, 3)
9

[1 3 7]
[3 5 1]
[[ 1 -1]
 [ 3  5]]
